[package]
name = "backed_array"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["zstd"]
zstd = ["dep:zstd"]
#zstd-thin-lto = ["zstd", "zstd/thin-lto", "zstd/fat-lto"]
#zstd-fat-lto = ["zstd", "zstd/fat-lto"]
zstdmt = ["zstd", "zstd/zstdmt"]
async = ["dep:async-bincode", "dep:tokio", "dep:tokio-util", "dep:futures"]
async-zstd = ["async", "dep:async-compression"]
async-zstdmt = ["async-zstd", "async-compression/zstdmt"]

[dependencies]
bincode = "1.3.3"
itertools = "0.12.1"
serde = { version = "1.0.197", features = ["derive"] }
derive-getters = "0.3.0"
uuid = { version = "1.8.0", features = ["v4"] }

zstd = { version = "0.13.1", optional = true }

async-compression = { version = "0.4.8", optional = true }
async-bincode = { version = "0.7.2", optional = true }
tokio = { version = "1.37.0", optional = true, features = ["rt", "io-util", "fs"] }
tokio-util = { version = "0.7.10", optional = true, features = ["io", "io-util"] }
futures =  { version = "0.3.30", optional = true }

[dev-dependencies]
tokio = { version = "1.37.0", features = ["rt", "io-util", "fs", "macros"] }
