# See https://crates.io/crates/cargo-hack
name: feature-builds

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_features:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack
    - run: |
        cargo hack --each-feature build --ignore-private
        cargo hack --each-feature test --ignore-private --no-run 
