# From https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version
# See https://crates.io/crates/cargo-hack
name: msrv

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@cargo-hack
    - run: cargo hack check --version-range 1.79 --all-targets --ignore-private
