name: test

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        arch: [x86_64]
        include:
          - os: macos
            arch: arm
            triple: aarch64-apple-darwin
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: dtolnay/rust-toolchain@stable
      if: ${{ matrix.triple == null }}
    - uses: dtolnay/rust-toolchain@stable
      if: ${{ matrix.triple }}
      with:
        target: ${{ matrix.triple }}

    - name: Install libsodium (Ubuntu)
      if: ${{ matrix.os == 'ubuntu' }}
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: libsodium-dev

    - name: Install libsodium (MacOS)
      if: ${{ matrix.os == 'macos' }}
      run: brew install libsodium

    - name: Install libsodium (Windows)
      if: ${{ matrix.os == 'windows' }}
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.bat
        ./vcpkg install libsodium
        ./vcpkg integrate install

    - uses: Swatinem/rust-cache@v2

    - run: cargo test --verbose --all-features
